/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 rocket.glb --transform
Author: lizlancaster (https://sketchfab.com/lizlancaster)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/rocket-9b9b64b138f24e4a908238c0b471930e
Title: Rocket 🚀
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/rocket-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.94}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group position={[0, 0, 0.87]} rotation={[-Math.PI / 2, 0, -2.6]} scale={100}>
            <mesh geometry={nodes.Cylinder_Charcoal_0.geometry} material={materials.Charcoal} />
            <mesh geometry={nodes.Cylinder_Gloss_Red_0.geometry} material={materials.Gloss_Red} />
            <mesh geometry={nodes.Cylinder_Gloss_White_0.geometry} material={materials.Gloss_White} />
            <mesh geometry={nodes.Cylinder_Material001_0.geometry} material={materials['Material.001']} />
            <mesh geometry={nodes.Cylinder_White_Glow_0.geometry} material={materials.White_Glow} />
          </group>
          <mesh geometry={nodes.Icosphere_Flame_0.geometry} material={materials.material_0} position={[0, -145.48, 0]} rotation={[1.6, -0.01, 0.72]} scale={72.66} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/rocket-transformed.glb')
